version: "3.8"
services:
  mongodb:
    image: 'mongo'
    ports:
      - '27017:27017'
    volumes:
      - data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
  server:
    build: ./server
    ports:
      - '3001:3001'
    volumes:
      - ./server:/app
      - /app/node_modules
    env_file:
      - ./server/.env
    depends_on:
      - mongodb
  client:
    build:
      context: ./
      dockerfile: ./client/Dockerfile
    ports:
      - '3000:3000'
    volumes:
      - ./client:/app/client
      - ./@types:/app/@types
      - /app/node_modules
volumes:
  data:
