# docker exec -t -i mycontainer /bin/bash
version: '3.8'
services:
  mongodb:
    image: 'mongo'
    ports:
      - '27017:27017'
    volumes:
      - data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    logging:
      driver: 'none'
  server:
    build:
      context: ./
      dockerfile: Dockerfile
      target: prod
      args:
        - FIREBASE_API_KEY=${NEXT_PUBLIC_FIREBASE_API_KEY}
        - FIREBASE_AUTH_DOMAIN=${NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN}
        - FIREBASE_PROJECT_ID=${NEXT_PUBLIC_FIREBASE_PROJECT_ID}
        - FIREBASE_SENDER_ID=${NEXT_PUBLIC_FIREBASE_SENDER_ID}
        - FIREBASE_APP_ID=${NEXT_PUBLIC_FIREBASE_APP_ID}
        - FIREBASE_MEASUREMENT_ID=${NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID}
    ports:
      - '3001:3001'
    volumes:
      - /app/node_modules
    env_file:
      - .env
    environment:
      MONGODB_USER: root
      MONGODB_PASSWORD: password
      MONGODB_URL: mongodb://USER:PASSWORD@mongodb:27017/james-giesbrecht
      NODE_ENV: production
    depends_on:
      - mongodb
volumes:
  data:
